
---
title: "Logistic Regression for Entity Resolution"
author: "STA 325: Homework 3"
output: 
     pdf_document:
      includes: 
          in_header: custom2.tex
font-size: 8px
---

***General instructions for homeworks***: Your code must be completely reproducible and must compile. No late homeworks will be accepted.

***Advice***: Start early on the homeworks and it is advised that you not wait until the day of as these homeworks are meant to be longer and treated as case studies.

***Commenting code***
Code should be commented. See the Google style guide for questions regarding commenting or how to write code \url{https://google.github.io/styleguide/Rguide.xml}.

***R Markdown Test***

0. Open a new R Markdown file; set the output to HTML mode and "Knit". This should produce a web page with the knitting procedure executing your code blocks. You can edit this new file to produce your homework submission.


\textbf{Total points on assignment: 5 (reproducibility) + 12 points for the assignment.}

Download/install the RecordLinkage and tree libraries. You will use the RLdata500 data set in R which you can load into your workspace by (after typing the command library(RecordLinkage)) typing data(RLdata500). Typing ls( ) then shows two objects -- the actual text data RLdata500 and identity.RLdata500, which are the unique identifiers. See help(RLdata500) for additional details. 


```{r, include = FALSE}
library(RecordLinkage)
library(xtable)
source("calc.pcs.R")
```



Our goal is to build supervised models to predict whether or not pairs of records match. 

To do so, we need labels (which we have, luckily, using identity.RLdata500) and similarity metrics for the 124,750 pairs of records.




1. (5 points) Create a matrix with 124,750 rows and 8 columns. The rows correspond to pairs of records. Columns correspond to the similarity metric for the different fields for the pair of records. For example, the first row would be for the record pair (1,2); the second row for (1,3), etc. The first column is for fname c1, the second for fname c2, etc. The last column is a binary indicator of whether or not that pair of records matches (1 = yes; 0 = no).



Fill in the first seven columns of your matrix with the Jaro-Winkler scores for each field; the last column should indicate match/non-match. In this problem, treat all fields as text strings, even the birthdate information.

The JW score requires character strings; you may need to use as.character( ) on the field values. Also, if one or both of the strings is NA, JW = NA.

One coding suggestion would be to first create a 500 x 500 matrix of JW scores for each field and then build the larger matrix by extracting the upper triangular part of the matrices for each field.



2. (5 points) Use your matrix to fit a logistic regression model predicting whether or not the pairs of records are a match using all fields except fname c2, lname c2 as predictor variables. Which fields were significant predictors of being a match? Does anything surprise you? Can you think of why this might have happened by digging more into the data set and thinking about if the model is appropriate for this data set. 


3. (2 points) In the above, we chose to treat the numeric birthday variables as text (reasonable assumption). What if instead of using a JW score, we just used exact matching on birth year, month, and day? How would that change our results from 2)? 


